syntax enable 

" Colorschemes
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set background=dark
colorscheme nachtleben
set t_Co=256
set termguicolors

" General options
set tabstop=4
set softtabstop=4
set number
set showcmd
set cursorline
filetype plugin indent on
set lazyredraw
set showmatch
set hlsearch
set ic

" keybinds
nnoremap <leader><space> :nohlsearch<CR> 

" i3conf syntax detection
aug i3config_ft_detection
  au!
  au BufNewFile,BufRead ~/.config/i3/config set filetype=i3config
aug end
