syntax enable 
set background=dark
colorscheme solarized
set tabstop=4
set softtabstop=4
set number
set showcmd
set cursorline
filetype plugin indent on
set lazyredraw
set showmatch
set hlsearch
set incsearch
nnoremap <leader><space> :nohlsearch<CR>
