#!/usr/bin/env python3

"""
This script uses nyaa.si's rss feed to automatically download anime
"""
import feedparser
import configparser
import os
import shutil
import datetime

feed = feedparser.parse('https://nyaa.si/?page=rss')
number_dl = 0
conf_path = os.environ['HOME'] + "/.config/nyaa-dl/nyaa-dl.ini"

def write_settings():
    print("Set download path (This is where the torrents would be stored): ")
    dl_path = input()

    print("Set ingest path (This is where transmission would get the torrents): ")
    in_path = input()

    print("Set watch list path: ")
    wl_path = input()

    config = configparser.ConfigParser()
    config.read(conf_path)
    config.add_section('Settings')
    config.set('Settings', 'download-path', dl_path)
    config.set('Settings', 'watch-list-path', wl_path)
    config.set('Settings', 'ingest-path', in_path)

    with open(conf_path, 'w') as f:
        config.write(f)

def read_dl_path():
    config = configparser.ConfigParser()
    config.read(conf_path)
    dl_path = config.get('Settings', 'download-path')
    return dl_path
    
def read_in_path():
    config = configparser.ConfigParser()
    config.read(conf_path)
    in_path = config.get('Settings', 'ingest-path')
    return in_path

def read_watch_list_file():
    config = configparser.ConfigParser()
    config.read(conf_path)
    wl_path = config.get('Settings', 'watch-list-path') + "/watch-list.txt"
    return wl_path

def read_watch_list():
    wList = [line.rstrip('\n') for line in open(read_watch_list_file())]
    return wList

def exit_message():
    log_path = os.environ["HOME"] + "/.config/nyaa-dl/nyaa-dl.log"
    if number_dl != 0:
        message = str(number_dl) + " files downloaded."
        print(message)
        log = open(log_path, 'a')
        log.write(message + '\n')
        log.close()
        exit()
    else:
        message = "All anime up to date."
        print(message)
        log = open(log_path, 'a')
        log.write(message + '\n')
        log.close()
        exit()

def dl_torrent(feed):
    log_path = os.environ["HOME"] + "/.config/nyaa-dl/nyaa-dl.log"
    timestamp = datetime.datetime.now()
    ts = timestamp.strftime("%Y-%m-%d %H:%M:%S")
    time_log = open(log_path, 'a')
    time_log.write('\n' + "[" + ts + "]" + '\n')
    time_log.close()
    for post in feed.entries:
        animes = read_watch_list()
        for anime in animes:
            if anime in post.title:
                if ("1080p" in post.title):
                    dlpath = read_dl_path()
                    inpath = read_in_path()

                    file_num = len([name for name in os.listdir(dlpath) if os.path.isfile(os.path.join(dlpath, name))])

                    cmd = "wget -nc -P " + dlpath + " " + post.link + " > /dev/null 2>&1 "
                    os.system(cmd)

                    file_num_new = len([name for name in os.listdir(dlpath) if os.path.isfile(os.path.join(dlpath, name))])

                    if file_num_new > file_num:
                        message = '"' + post.title + '"' + " was downloaded."
                        print(message)
                        log = open(log_path, 'a')
                        log.write(message + '\n')
                        log.close()

                        link = post.link
                        link_new = link.replace("https://nyaa.si/download/", '')
                        srcpath = dlpath + "/" + link_new
                        dstpath = inpath + "/" + link_new

                        shutil.copyfile(srcpath, dstpath)

                        global number_dl
                        number_dl = number_dl + 1
                    else:
                        print(anime + " is up to date.")

if __name__ == '__main__':
    if os.path.exists(conf_path):
        dl_torrent(feed)
        exit_message()
    else:
        write_settings()
        dl_torrent(feed)
        exit_message()